using NJsonSchema;

namespace DotSchema.Generators;

/// <summary>
///     Cleans up verbose type names generated by schemars/NJsonSchema.
///     Detects conjunction patterns (e.g., _and_, _or_, _with_) and extracts meaningful type names.
///     Optionally renames the root type to "{Variant}{RootTypeName}" when variant is specified.
///     Prefixes conflicting types (same name, different content across variants) with the variant name.
/// </summary>
public sealed class CleanTypeNameGenerator : ITypeNameGenerator
{
    private readonly IReadOnlySet<string> _conflictingTypes;
    private readonly string _rootTypeName;
    private readonly string? _variant;

    /// <summary>
    ///     Creates a generator without variant-specific renaming (for schema analysis).
    /// </summary>
    public CleanTypeNameGenerator()
    {
        _variant = null;
        _conflictingTypes = new HashSet<string>();
        _rootTypeName = Constants.DefaultRootTypeName;
    }

    /// <summary>
    ///     Creates a generator that renames the root type to "{variant}{rootTypeName}"
    ///     and prefixes conflicting types with the variant name.
    /// </summary>
    public CleanTypeNameGenerator(string variant, string rootTypeName, IReadOnlySet<string>? conflictingTypes = null)
    {
        _variant = variant;
        _rootTypeName = rootTypeName;
        _conflictingTypes = conflictingTypes ?? new HashSet<string>();
    }

    public string Generate(JsonSchema schema, string? typeNameHint, IEnumerable<string> reservedTypeNames)
    {
        var name = typeNameHint ?? schema.Title ?? Constants.AnonymousTypeName;

        // Try to clean up conjunction-based names (e.g., FlattenedValue_X_and_ConfigMetadata)
        name = CleanConjunctionName(name);

        // Remove any remaining underscores
        name = name.Replace("_", "");

        // Remove generic type syntax which is invalid in C# type names
        // e.g., "ParsedFileOutput<HostsFile>" -> "ParsedFileOutputHostsFile"
        name = name.Replace("<", "").Replace(">", "");

        // Rename root type to "{Variant}{RootTypeName}" if variant is specified
        if (name == _rootTypeName && !string.IsNullOrEmpty(_variant))
        {
            name = $"{_variant}{_rootTypeName}";
        }

        // Prefix conflicting types with variant name (e.g., ProcessConfig -> WindowsProcessConfig)
        if (_conflictingTypes.Contains(name) && !string.IsNullOrEmpty(_variant))
        {
            name = $"{_variant}{name}";
        }

        // Ensure unique name
        var baseName = name;
        var counter = 1;

        while (reservedTypeNames.Contains(name))
        {
            name = $"{baseName}{counter++}";
        }

        return name;
    }

    /// <summary>
    ///     Cleans up type names that contain conjunctions (e.g., _and_, _or_, _with_).
    ///     Extracts the meaningful parts and combines them into a clean type name.
    /// </summary>
    private static string CleanConjunctionName(string name)
    {
        // Find which conjunction is used (if any)
        var conjunction = Constants.Conjunctions.FirstOrDefault(c => name.Contains(c, StringComparison.Ordinal));

        if (conjunction == null)
        {
            return name;
        }

        // Split on the conjunction
        var parts = name.Split(conjunction, StringSplitOptions.RemoveEmptyEntries);

        if (parts.Length < 2)
        {
            return name;
        }

        // Process the left part: strip the first segment (wrapper type like FlattenedValue)
        var leftPart = StripFirstSegment(parts[0]);

        // Append the right part as-is (no special suffix handling)
        var rightPart = parts[^1];

        return $"{leftPart}{rightPart}";
    }

    /// <summary>
    ///     Strips the first underscore-delimited segment from a name.
    ///     E.g., "FlattenedValue_ActiveUsersCollector" -> "ActiveUsersCollector"
    /// </summary>
    private static string StripFirstSegment(string name)
    {
        var firstUnderscore = name.IndexOf('_');

        return firstUnderscore >= 0 ? name[(firstUnderscore + 1)..] : name;
    }
}
