using System.Text.RegularExpressions;

namespace DotSchema;

/// <summary>
///     Post-processes generated C# code to clean up and transform type definitions.
///     Uses compiled regex patterns for better performance.
/// </summary>
public static partial class CodePostProcessor
{
    /// <summary>
    ///     Maximum number of recursive iterations to prevent infinite loops.
    /// </summary>
    private const int MaxRemoveIterations = 100;

    // Compiled regex patterns for performance
    [GeneratedRegex(
        @"//----------------------\s*\n// <auto-generated>.*?</auto-generated>\s*\n//----------------------\s*\n",
        RegexOptions.Singleline)]
    private static partial Regex AutoGeneratedCommentRegex();

    [GeneratedRegex(
        @"\s*private System\.Collections\.Generic\.IDictionary<string, object>\? _additionalProperties;\s*"
        + @"\[System\.Text\.Json\.Serialization\.JsonExtensionData\]\s*"
        + @"public System\.Collections\.Generic\.IDictionary<string, object> AdditionalProperties\s*"
        + @"\{\s*get \{ return _additionalProperties \?\? \(_additionalProperties = new System\.Collections\.Generic\.Dictionary<string, object>\(\)\); \}\s*"
        + @"set \{ _additionalProperties = value; \}\s*\}",
        RegexOptions.Singleline)]
    private static partial Regex AdditionalPropertiesRegex();

    /// <summary>
    ///     Processes generated code based on the generation mode.
    ///     Note: Type renaming (RootType -> {Variant}RootType) is now handled by CleanTypeNameGenerator
    ///     during code generation, not here.
    /// </summary>
    public static string Process(
        string code,
        GenerationMode mode,
        string variant,
        HashSet<string> sharedTypes,
        HashSet<string> variantTypes,
        HashSet<string> conflictingTypes,
        string rootTypeName,
        bool generateInterface = true)
    {
        return mode switch
        {
            GenerationMode.Shared => CleanupSharedCode(code, variantTypes, conflictingTypes, rootTypeName),
            GenerationMode.Variant => CleanupVariantCode(code, sharedTypes, variant, rootTypeName, generateInterface),
            _ => CleanupAllCode(code)
        };
    }

    private static string CleanupSharedCode(
        string code,
        HashSet<string> variantSpecificTypes,
        HashSet<string> conflictingTypes,
        string rootTypeName)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Collect all types to remove in a single set for single-pass removal
        var typesToRemove = new HashSet<string>(variantSpecificTypes);
        typesToRemove.UnionWith(conflictingTypes);
        typesToRemove.Add(rootTypeName); // Remove the root type class (it's variant-specific)

        // Remove all types in a single pass
        code = RemoveTypesBatch(code, typesToRemove);

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    private static string CleanupVariantCode(
        string code,
        HashSet<string> sharedTypes,
        string variant,
        string rootTypeName,
        bool generateInterface)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Remove shared types from variant-specific code in a single pass
        code = RemoveTypesBatch(code, sharedTypes);

        // Add I{RootType} interface to the root variant config class (if enabled)
        if (generateInterface && !string.IsNullOrEmpty(variant))
        {
            code = AddRootTypeInterface(code, variant, rootTypeName);
        }

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    /// <summary>
    ///     Converts partial classes to sealed classes, except for base classes that are inherited from.
    ///     Generated DTO classes should not be inherited from unless they are base types.
    /// </summary>
    private static string MakeClassesSealed(string code)
    {
        // Find all base classes (classes that are inherited from)
        // Pattern matches: "class SomeClass : BaseClassName" or "class SomeClass : BaseClassName,"
        var baseClasses = InheritanceRegex()
                          .Matches(code)
                          .Select(m => m.Groups[1].Value)
                          .ToHashSet();

        // Replace "public partial class ClassName" with "public sealed class ClassName"
        // but only if ClassName is not a base class
        return ClassDeclarationRegex()
            .Replace(
                code,
                match =>
                {
                    var className = match.Groups[1].Value;

                    return baseClasses.Contains(className)
                        ? match.Value // Keep as partial class (base class)
                        : $"public sealed class {className}";
                });
    }

    [GeneratedRegex(@"class\s+\w+\s*:\s*(\w+)")]
    private static partial Regex InheritanceRegex();

    [GeneratedRegex(@"public partial class (\w+)")]
    private static partial Regex ClassDeclarationRegex();

    /// <summary>
    ///     Adds the I{RootType} interface to the root variant config class.
    ///     Transforms: "public partial class WindowsConfig" -> "public partial class WindowsConfig : IConfig"
    /// </summary>
    private static string AddRootTypeInterface(string code, string variant, string rootTypeName)
    {
        var configClassName = $"{variant}{rootTypeName}";
        var interfaceName = Constants.GetInterfaceName(rootTypeName);

        // NJsonSchema generates "public partial class {Name}", so check for that first
        var classDeclaration = $"public partial class {configClassName}";
        var classIndex = code.IndexOf(classDeclaration, StringComparison.Ordinal);

        // Fall back to non-partial class if not found
        if (classIndex == -1)
        {
            classDeclaration = $"public class {configClassName}";
            classIndex = code.IndexOf(classDeclaration, StringComparison.Ordinal);
        }

        if (classIndex == -1)
        {
            return code;
        }

        // Check if it already has an inheritance (: something)
        var afterDeclaration = classIndex + classDeclaration.Length;
        var nextNonWhitespace = afterDeclaration;

        while (nextNonWhitespace < code.Length && char.IsWhiteSpace(code[nextNonWhitespace]))
        {
            nextNonWhitespace++;
        }

        if (nextNonWhitespace < code.Length && code[nextNonWhitespace] == ':')
        {
            // Already has inheritance, just add interface to the list
            // Find the position after the colon and any whitespace
            var colonPos = nextNonWhitespace + 1;

            while (colonPos < code.Length && char.IsWhiteSpace(code[colonPos]))
            {
                colonPos++;
            }

            // Insert "{InterfaceName}, " before the existing base type
            return code[..colonPos] + $"{interfaceName}, " + code[colonPos..];
        }

        // No inheritance - add ": {InterfaceName}" after the class name
        return code[..afterDeclaration] + $" : {interfaceName}" + code[afterDeclaration..];
    }

    private static string CleanupAllCode(string code)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    private static string RemoveAdditionalPropertiesBoilerplate(string code)
    {
        // Remove the <auto-generated> comment block so JetBrains cleanup will process the file
        code = AutoGeneratedCommentRegex().Replace(code, "");

        return AdditionalPropertiesRegex().Replace(code, "");
    }

    /// <summary>
    ///     Removes all specified types from the code in a single pass by finding all type boundaries
    ///     first, then building the result string without the removed sections.
    /// </summary>
    private static string RemoveTypesBatch(string code, HashSet<string> typeNames)
    {
        if (typeNames.Count == 0)
        {
            return code;
        }

        // Find all type definition ranges to remove
        var rangesToRemove = new List<(int Start, int End)>();

        foreach (var typeName in typeNames)
        {
            // Find as both class and enum
            FindTypeRanges(code, typeName, "public partial class ", rangesToRemove);
            FindTypeRanges(code, typeName, "public enum ", rangesToRemove);
        }

        if (rangesToRemove.Count == 0)
        {
            return code;
        }

        // Sort ranges by start position and merge overlapping ranges
        rangesToRemove.Sort((a, b) => a.Start.CompareTo(b.Start));
        var mergedRanges = MergeOverlappingRanges(rangesToRemove);

        // Build result string by copying non-removed sections
        var result = new System.Text.StringBuilder(code.Length);
        var currentPos = 0;

        foreach (var (start, end) in mergedRanges)
        {
            if (start > currentPos)
            {
                result.Append(code, currentPos, start - currentPos);
            }

            currentPos = end;
        }

        // Append remaining code after last removal
        if (currentPos < code.Length)
        {
            result.Append(code, currentPos, code.Length - currentPos);
        }

        return result.ToString();
    }

    /// <summary>
    ///     Finds all occurrences of a type definition and adds their ranges to the list.
    /// </summary>
    private static void FindTypeRanges(
        string code,
        string typeName,
        string typeKeyword,
        List<(int Start, int End)> ranges)
    {
        var searchPattern = typeKeyword + typeName;
        var searchStart = 0;

        while (searchStart < code.Length)
        {
            var typeIndex = code.IndexOf(searchPattern, searchStart, StringComparison.Ordinal);

            if (typeIndex == -1)
            {
                break;
            }

            // Make sure we're matching the exact type name (not a prefix)
            var afterName = typeIndex + searchPattern.Length;

            if (afterName < code.Length)
            {
                var nextChar = code[afterName];

                // Valid next characters: whitespace, newline, colon (for inheritance), open brace
                if (char.IsLetterOrDigit(nextChar) || nextChar == '_')
                {
                    // This is a prefix match (e.g., "Config" matching "ConfigMetadata"), skip it
                    searchStart = typeIndex + 1;

                    continue;
                }
            }

            // Find the full range of this type definition
            var range = GetTypeDefinitionRange(code, typeIndex);

            if (range.HasValue)
            {
                ranges.Add(range.Value);
                searchStart = range.Value.End;
            }
            else
            {
                searchStart = typeIndex + 1;
            }
        }
    }

    /// <summary>
    ///     Gets the full range of a type definition including doc comments and attributes.
    /// </summary>
    private static (int Start, int End)? GetTypeDefinitionRange(string code, int typeIndex)
    {
        // Find the start of the definition by looking backwards for preceding elements
        var definitionStart = typeIndex;

        // Look backwards for [GeneratedCode...] attribute - but only within reasonable distance (200 chars)
        var searchStart = Math.Max(0, typeIndex - 200);
        var beforeType = code[searchStart..typeIndex];
        var attrIndex = beforeType.LastIndexOf("[System.CodeDom.Compiler.GeneratedCode", StringComparison.Ordinal);

        if (attrIndex != -1)
        {
            definitionStart = searchStart + attrIndex;

            // Look backwards for /// <summary> doc comment
            var docSearchStart = Math.Max(0, definitionStart - 300);
            var docCommentSearch = code[docSearchStart..definitionStart].TrimEnd();

            if (docCommentSearch.EndsWith("</summary>", StringComparison.Ordinal))
            {
                var summaryIndex = docCommentSearch.LastIndexOf("/// <summary>", StringComparison.Ordinal);

                if (summaryIndex != -1)
                {
                    definitionStart = docSearchStart + summaryIndex;
                }
            }
        }

        // Find the closing brace of the type - use brace counting
        var braceStart = code.IndexOf('{', typeIndex);

        if (braceStart == -1)
        {
            return null;
        }

        var braceCount = 1;
        var definitionEnd = braceStart + 1;

        while (definitionEnd < code.Length && braceCount > 0)
        {
            if (code[definitionEnd] == '{')
            {
                braceCount++;
            }
            else if (code[definitionEnd] == '}')
            {
                braceCount--;
            }

            definitionEnd++;
        }

        return (definitionStart, definitionEnd);
    }

    /// <summary>
    ///     Merges overlapping or adjacent ranges into a single list of non-overlapping ranges.
    /// </summary>
    private static List<(int Start, int End)> MergeOverlappingRanges(List<(int Start, int End)> sortedRanges)
    {
        var merged = new List<(int Start, int End)>();

        foreach (var range in sortedRanges)
        {
            if (merged.Count == 0 || merged[^1].End < range.Start)
            {
                merged.Add(range);
            }
            else
            {
                // Extend the last range if overlapping
                var last = merged[^1];
                merged[^1] = (last.Start, Math.Max(last.End, range.End));
            }
        }

        return merged;
    }
}
