using System.Text.RegularExpressions;

namespace DotSchema;

/// <summary>
///     Post-processes generated C# code to clean up and transform type definitions.
///     Uses compiled regex patterns for better performance.
/// </summary>
public static partial class CodePostProcessor
{
    /// <summary>
    ///     Maximum number of recursive iterations to prevent infinite loops.
    /// </summary>
    private const int MaxRemoveIterations = 100;

    // Compiled regex patterns for performance
    [GeneratedRegex(
        @"//----------------------\s*\n// <auto-generated>.*?</auto-generated>\s*\n//----------------------\s*\n",
        RegexOptions.Singleline)]
    private static partial Regex AutoGeneratedCommentRegex();

    [GeneratedRegex(
        @"\s*private System\.Collections\.Generic\.IDictionary<string, object>\? _additionalProperties;\s*"
        + @"\[System\.Text\.Json\.Serialization\.JsonExtensionData\]\s*"
        + @"public System\.Collections\.Generic\.IDictionary<string, object> AdditionalProperties\s*"
        + @"\{\s*get \{ return _additionalProperties \?\? \(_additionalProperties = new System\.Collections\.Generic\.Dictionary<string, object>\(\)\); \}\s*"
        + @"set \{ _additionalProperties = value; \}\s*\}",
        RegexOptions.Singleline)]
    private static partial Regex AdditionalPropertiesRegex();

    /// <summary>
    ///     Processes generated code based on the generation mode.
    ///     Note: Type renaming (RootType -> {Variant}RootType) is now handled by CleanTypeNameGenerator
    ///     during code generation, not here.
    /// </summary>
    public static string Process(
        string code,
        GenerationMode mode,
        string variant,
        HashSet<string> sharedTypes,
        HashSet<string> variantTypes,
        HashSet<string> conflictingTypes,
        string rootTypeName,
        bool generateInterface = true)
    {
        return mode switch
        {
            GenerationMode.Shared => CleanupSharedCode(code, variantTypes, conflictingTypes, rootTypeName),
            GenerationMode.Variant => CleanupVariantCode(code, sharedTypes, variant, rootTypeName, generateInterface),
            _ => CleanupAllCode(code)
        };
    }

    private static string CleanupSharedCode(
        string code,
        HashSet<string> variantSpecificTypes,
        HashSet<string> conflictingTypes,
        string rootTypeName)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Remove the root type class (it's variant-specific)
        code = RemoveClassByName(code, rootTypeName);

        // Remove variant-specific types from shared code
        foreach (var typeName in variantSpecificTypes)
        {
            code = RemoveClassByName(code, typeName);
            code = RemoveEnumByName(code, typeName);
        }

        // Remove conflicting types from shared code (they have different content per variant)
        foreach (var typeName in conflictingTypes)
        {
            code = RemoveClassByName(code, typeName);
            code = RemoveEnumByName(code, typeName);
        }

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    private static string CleanupVariantCode(
        string code,
        HashSet<string> sharedTypes,
        string variant,
        string rootTypeName,
        bool generateInterface)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Remove shared types from variant-specific code
        foreach (var typeName in sharedTypes)
        {
            code = RemoveClassByName(code, typeName);
            code = RemoveEnumByName(code, typeName);
        }

        // Add I{RootType} interface to the root variant config class (if enabled)
        if (generateInterface && !string.IsNullOrEmpty(variant))
        {
            code = AddRootTypeInterface(code, variant, rootTypeName);
        }

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    /// <summary>
    ///     Converts partial classes to sealed classes, except for base classes that are inherited from.
    ///     Generated DTO classes should not be inherited from unless they are base types.
    /// </summary>
    private static string MakeClassesSealed(string code)
    {
        // Find all base classes (classes that are inherited from)
        // Pattern matches: "class SomeClass : BaseClassName" or "class SomeClass : BaseClassName,"
        var baseClasses = InheritanceRegex()
                          .Matches(code)
                          .Select(m => m.Groups[1].Value)
                          .ToHashSet();

        // Replace "public partial class ClassName" with "public sealed class ClassName"
        // but only if ClassName is not a base class
        return ClassDeclarationRegex()
            .Replace(
                code,
                match =>
                {
                    var className = match.Groups[1].Value;

                    return baseClasses.Contains(className)
                        ? match.Value // Keep as partial class (base class)
                        : $"public sealed class {className}";
                });
    }

    [GeneratedRegex(@"class\s+\w+\s*:\s*(\w+)")]
    private static partial Regex InheritanceRegex();

    [GeneratedRegex(@"public partial class (\w+)")]
    private static partial Regex ClassDeclarationRegex();

    /// <summary>
    ///     Adds the I{RootType} interface to the root variant config class.
    ///     Transforms: "public partial class WindowsConfig" -> "public partial class WindowsConfig : IConfig"
    /// </summary>
    private static string AddRootTypeInterface(string code, string variant, string rootTypeName)
    {
        var configClassName = $"{variant}{rootTypeName}";
        var interfaceName = Constants.GetInterfaceName(rootTypeName);

        // NJsonSchema generates "public partial class {Name}", so check for that first
        var classDeclaration = $"public partial class {configClassName}";
        var classIndex = code.IndexOf(classDeclaration, StringComparison.Ordinal);

        // Fall back to non-partial class if not found
        if (classIndex == -1)
        {
            classDeclaration = $"public class {configClassName}";
            classIndex = code.IndexOf(classDeclaration, StringComparison.Ordinal);
        }

        if (classIndex == -1)
        {
            return code;
        }

        // Check if it already has an inheritance (: something)
        var afterDeclaration = classIndex + classDeclaration.Length;
        var nextNonWhitespace = afterDeclaration;

        while (nextNonWhitespace < code.Length && char.IsWhiteSpace(code[nextNonWhitespace]))
        {
            nextNonWhitespace++;
        }

        if (nextNonWhitespace < code.Length && code[nextNonWhitespace] == ':')
        {
            // Already has inheritance, just add interface to the list
            // Find the position after the colon and any whitespace
            var colonPos = nextNonWhitespace + 1;

            while (colonPos < code.Length && char.IsWhiteSpace(code[colonPos]))
            {
                colonPos++;
            }

            // Insert "{InterfaceName}, " before the existing base type
            return code[..colonPos] + $"{interfaceName}, " + code[colonPos..];
        }

        // No inheritance - add ": {InterfaceName}" after the class name
        return code[..afterDeclaration] + $" : {interfaceName}" + code[afterDeclaration..];
    }

    private static string CleanupAllCode(string code)
    {
        code = RemoveAdditionalPropertiesBoilerplate(code);

        // Make all classes sealed
        code = MakeClassesSealed(code);

        return code;
    }

    private static string RemoveAdditionalPropertiesBoilerplate(string code)
    {
        // Remove the <auto-generated> comment block so JetBrains cleanup will process the file
        code = AutoGeneratedCommentRegex().Replace(code, "");

        return AdditionalPropertiesRegex().Replace(code, "");
    }

    private static string RemoveClassByName(string code, string className)
    {
        return RemoveTypeByName(code, className, false);
    }

    private static string RemoveEnumByName(string code, string enumName)
    {
        return RemoveTypeByName(code, enumName, true);
    }

    private static string RemoveTypeByName(
        string code,
        string typeName,
        bool isEnum,
        int remainingIterations = MaxRemoveIterations)
    {
        // Guard against infinite loops
        if (remainingIterations <= 0)
        {
            return code;
        }

        // Find the start of the type definition (look for GeneratedCode attribute before the type)
        var typeKeyword = isEnum ? "public enum " : "public partial class ";
        var searchPattern = typeKeyword + typeName;

        var typeIndex = code.IndexOf(searchPattern, StringComparison.Ordinal);

        if (typeIndex == -1)
        {
            return code;
        }

        // Make sure we're matching the exact type name (not a prefix)
        var afterName = typeIndex + searchPattern.Length;

        if (afterName < code.Length)
        {
            var nextChar = code[afterName];

            // Valid next characters: whitespace, newline, colon (for inheritance), open brace
            if (char.IsLetterOrDigit(nextChar) || nextChar == '_')
            {
                // This is a prefix match (e.g., "Config" matching "ConfigMetadata"), skip it
                var remainingCode = code[(typeIndex + 1)..];
                var laterMatch = RemoveTypeByName(remainingCode, typeName, isEnum, remainingIterations - 1);

                return code[..(typeIndex + 1)] + laterMatch;
            }
        }

        // Find the start of the definition by looking backwards for preceding elements
        var definitionStart = typeIndex;

        // Look backwards for [GeneratedCode...] attribute - but only within reasonable distance (200 chars)
        var searchStart = Math.Max(0, typeIndex - 200);
        var beforeType = code[searchStart..typeIndex];
        var attrIndex = beforeType.LastIndexOf("[System.CodeDom.Compiler.GeneratedCode", StringComparison.Ordinal);

        if (attrIndex != -1)
        {
            definitionStart = searchStart + attrIndex;

            // Look backwards for /// <summary> doc comment
            var docSearchStart = Math.Max(0, definitionStart - 300);
            var docCommentSearch = code[docSearchStart..definitionStart].TrimEnd();

            if (docCommentSearch.EndsWith("</summary>", StringComparison.Ordinal))
            {
                var summaryIndex = docCommentSearch.LastIndexOf("/// <summary>", StringComparison.Ordinal);

                if (summaryIndex != -1)
                {
                    definitionStart = docSearchStart + summaryIndex;
                }
            }
        }

        // Find the closing brace of the type - use brace counting
        var braceStart = code.IndexOf('{', typeIndex);

        if (braceStart == -1)
        {
            return code;
        }

        var braceCount = 1;
        var definitionEnd = braceStart + 1;

        while (definitionEnd < code.Length && braceCount > 0)
        {
            if (code[definitionEnd] == '{')
            {
                braceCount++;
            }
            else if (code[definitionEnd] == '}')
            {
                braceCount--;
            }

            definitionEnd++;
        }

        // Remove from definitionStart to definitionEnd
        var result = code[..definitionStart] + code[definitionEnd..];

        // Recursively remove if there are more instances
        return RemoveTypeByName(result, typeName, isEnum, remainingIterations - 1);
    }
}
